name: brainbox_qa
description: BrainBox QA - Premium mobile application for tracking app development projects.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true