name: brainbox_qa
description: BrainBox QA - Premium mobile application for tracking app development projects.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  intl: ^0.18.1
  url_launcher: ^6.2.2
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  path: ^1.8.3
  crypto: ^3.0.3
  http: ^1.1.0
  url_launcher_web: ^2.2.0
  url_launcher_android: ^6.2.0
  url_launcher_ios: ^6.2.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^0.3.0
  ffi: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true